In [1]:
import pandas as pd

In [2]:
data = [[1,2,3],[4,5,6],[7,8,9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
list('321')

['3', '2', '1']

In [10]:
df = pd.DataFrame(data, list('321'), list('ZYX'))
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [11]:
df.sort_index(inplace = True) #ordenando los indices
df

   Z  Y  X
1  7  8  9
2  4  5  6
3  1  2  3

In [12]:
df.sort_index(inplace = True, axis = 1)  #ordenando las columnas con axis
df

   X  Y  Z
1  9  8  7
2  6  5  4
3  3  2  1

In [13]:
df.sort_values(by = 'X' ,inplace = True)  #ordenando el contenido del DataFrame por los valores de la columna X en forma ascendente
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [14]:
df.sort_values(by = '3', axis = 1 ,inplace = True)  #ordenando el contenido del DataFrame por los valores de la fila 3 en forma ascendente y ordenacion columnar(?)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9